apiVersion: v1
kind: Service
metadata:
  name: bootstrap
  annotations:
    {{- toYaml .Values.listeners.broker.service.annotations | nindent 4 }}
  labels:
    {{- include "kafka.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.listeners.broker.service.type }}
  ports:
    - name: broker
      port: {{ .Values.listeners.broker.service.port }}
      targetPort: broker
      protocol: TCP
    {{- if and ( .Values.prometheus.jmx.enabled ) ( .Values.servicemonitor.enabled ) }}
    - name: jmx-prometheus
      port: {{ .Values.prometheus.jmx.port }}
      targetPort: jmx-prometheus
      protocol: TCP
    {{- end }}
  selector:
    app: {{ template "kafka.name" . }}
    release: {{ .Release.Name }}
