{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kafka.serviceAccountName" . }}
  labels:
    {{- include "kafka.labels.standard" . | nindent 4 }}
{{- end -}}
